### ISSUE TITLE
关于ivew的Icon更新问题

### ISSUE THREAD

**Issue by Mixiaowei** [zhouxianjun/iview-tree-table#3]
iview的3.x版本更新之后，Icon组件个别icon代码更改了，比如arrow-down-b改为了md-arrow-dropdown，所以iview3.x项目中引用此组件会导致三角图标不显示问题。

**Comment by zhouxianjun** [comment]
试试这个属性可以吗？
![image](https://user-images.githubusercontent.com/5254523/59174826-9b10ee00-8b85-11e9-9411-ad5b3da9b26f.png)

**Comment by Mixiaowei** [comment]
不行的，iview3.x的icon图标代码换了，上面的默认值arrow-right-b换成了md-arrow-dropright, arrow-down-b换成了md-arrow-dropdown；iview2.x不维护了。

**Comment by zhouxianjun** [comment]
![image](https://user-images.githubusercontent.com/5254523/59175499-5e92c180-8b88-11e9-9d06-c92912429173.png)
![image](https://user-images.githubusercontent.com/5254523/59175524-6f433780-8b88-11e9-9168-005e383156c7.png)
这样不行吗？

**Comment by Mixiaowei** [comment]
可以了，3ks
