### ISSUE TITLE
iview-tree-bable如果能提供最小最大高度设置更好，目前用于弹框不知道怎么限制高度，超过高度产生滚动条

### ISSUE THREAD

**Issue by mgxfm** [zhouxianjun/iview-tree-table#5]

**Comment by zhouxianjun** [comment]
你是说table的高度吗？

**Comment by mgxfm** [comment]
> 你是说table的高度吗？

是的，类似下面图片希望能有类似高度属性提供
![image](https://user-images.githubusercontent.com/20775871/64417065-f8f09b80-d0ca-11e9-963a-1f8b3e5deff5.png)

**Comment by zhouxianjun** [comment]
ok，我知道了。目前你如果急需的话。可以设置style 高度并且设置overflow。

**Comment by zhouxianjun** [comment]
固定表头后期加上去

**Comment by mgxfm** [comment]
> overflow

好的，感谢！！！

**Comment by zhouxianjun** [comment]
1.1.1版本已经新增了 height 与 maxHeight 参数。
